### ISSUE TITLE
wrong implementation of Ackley's function

### ISSUE THREAD

**Issue by yerrick** [eyounx/ZOOpt#1]
How I found the bug:
I ran an example to test, I changed the func code as
``` python
def myfunc(x):
	b=np.array(x)
	y = -20 * np.exp(-0.2 * np.sqrt(((b - 0.2)*(b - 0.2)).mean())) 
	- np.exp((np.cos(2 * math.pi * (b - 0.2))).mean()) + math.e + 20
	return y
```
and rerun the example in README. It got a different but better result than the original one, and then I found why original code is wrong:
```
T.dot return a scalar but not a list, so its mean is itself. 
```

Good luck.

**Comment by eyounx** [comment]
Thanks for your comment. Function corrected.
