### ISSUE TITLE
Infeasible solution of "High-dimensionality sequential random embedding "

### ISSUE THREAD

**Issue by dongquan11** [eyounx/ZOOpt#15]
Hello, I encountered the following problem while implementing Zoopt. Please help!
When I try to use SRE, the solved solution from Zoopt is outside of the constrained region of my problem (the unit box (0,1]**dim_size). Some elements in the solution is larger than 1 and some others are negative. In the paper cited in the documentation (https://doi.org/10.1613/jair.4806), it is said that if it is outside the feasible region it should be automatically projected back to this feasible region. Can you please verify?

This is my code where my objective function is to find the smallest eigenvalue of a matrix whose entries are computed via the variables:
_dim_size = 400
##### Constraints on the variables >0 and <=1
dim = Dimension(dim_size, [[1e-10, 1]] * dim_size, [True] * dim_size ) 
objective = Objective(smallest_eigen, dim)

low_dim = 100
uniform = list([1/2]*(low_dim+1))
initial = [uniform]
budget =5000
par = Parameter(budget=budget, init_samples = initial, precision = 1e-8, intermediate_result=True, high_dim_handling=True, reducedim=True, num_sre=5, low_dimension=Dimension(low_dim, [[1e-10, 1]] * low_dim, [True] * low_dim))

sol = Opt.min(objective, par)
optimal = sol.get_x()
optval= - sol.get_value()_

**Comment by AlexLiuyuren** [comment]
ZOOpt does not rescale the result at present, so it's normal that the solution is out of the search space. The easiest way to handle this is to rescale the result to the nearest bound by hand, e.g. the 3-D solution [-1, 0.5, 2], rescale to [1e10, 0.5, 1].  You can use 
```python
x = sol.get_x()
for i in range(len(x)):
    # rescale x[i]
```

**Comment by dongquan11** [comment]
Thank you !
