### ISSUE TITLE
Increasing the budget throws error in discrete search space

### ISSUE THREAD

**Issue by raam93** [eyounx/ZOOpt#16]
Hi, I implemented the following hypothetical minimization objective. The first part of the objective function is just a l1-norm while the second part ensures that the sum of first 3 entries of x equals to 1.
```
def fn(solution):
    x = solution.get_x() 
    x1 = [0,3,1,0,0]
    val = sum([abs(v-x1[i]) for i,v in enumerate(x)])+ ((np.sum([i for i in x[0:3]])-1.0)**2)
    return val

dim = 5
dimobj = Dimension(dim, regs=[[0,5]]*dim, tys=[False]*dim)
obj = Objective(fn, dimobj)
param = Parameter(budget=50)
solution = Opt.min(obj, param)
print(solution.get_x(), solution.get_value())
```

The above simple program works fine when the **budget is less than 50**. When I make it more than 50, it throws the following error:

```
ValueError: empty range for randrange() (0,0, 0)
``` 
Further, this problem occurs only when the search space is discrete. 

Any help much appreciated. Thanks!

**Comment by AlexLiuyuren** [comment]
I suppose there may be bugs in the implementation of discrete optimization. I'll fix it as soon as possible (May be in one week? I'm too busy these days, Sorry. I'll remind you when I fix it.). Thanks for your issue.

**Comment by AlexLiuyuren** [comment]
Bug fixed. Please update ZOOpt to the latest version by downloading the source code. Then  run following commands in your terminal
```python
python setup.py build
python setup.py install
```
and run your code again.
