### ISSUE TITLE
Stop criterion if objective value is not updated after certain numbers of iterations.

### ISSUE THREAD

**Issue by dongquan11** [eyounx/ZOOpt#19]
Hello, 

As indicated in the little, is it possible to include such stopping criterion? For example, if the intermediate objective values do not update (within precision 1e-5) more than 1000 iterations, stop and print the current best solution. 

Thank you in advance.

**Comment by AlexLiuyuren** [comment]
Thanks for your suggestion. I will add such stopping criterion and inform you as soon as it is implemented.

**Comment by AlexLiuyuren** [comment]
Please download the latest source code and update ZOOpt by
```
$ python setup.py build
$ python setup.py install
```
An example about how to use stopping criterion is shown in `example/simple_functions/opt_with_stopping_criterion.py`
We may publish the new version of ZOOpt which implements several more functions in few weeks.

**Comment by dongquan11** [comment]
Many thanks. I'm looking for the updated version of ZOOpt.
