### ISSUE TITLE
pip installation

### ISSUE THREAD

**Issue by NeillHerbst** [eyounx/ZOOpt#6]
I tried to install using `pip`. Seems like the `pareoopt` file is not included in the installation as I keep getting this error:

```
from paretoopt import ParetoOpt
ModuleNotFoundError: No module named 'paretoopt'
```

I used the following command: `pip install zoopt` on Windows 10.

**Comment by AlexLiuyuren** [comment]
I think you want to use ParetoOpt method (POSS). An example can be found [here](https://github.com/eyounx/ZOOpt/blob/master/example/sparse_regression/poss_opt.py).

**Comment by AlexLiuyuren** [comment]
Do I solve your problem? If there are some more questions, please feel free to let me know.

**Comment by NeillHerbst** [comment]
Sorry for only responding now. I think my initial code snippet is somewhat misleading. I'm trying to use the normal Zoopt optimization function. I upgraded from v0.1 to v0.2 and that error was raised when I tried to run the optimization function.

**Comment by AlexLiuyuren** [comment]
Could you post your specific code, especially the definition of `Objective` and `Parameter` objects? 
In addition, please try if the error is raised too when you run this [example](https://github.com/eyounx/ZOOpt/blob/master/example/sparse_regression/poss_opt.py).

**Comment by NeillHerbst** [comment]
I will give it a try tomorrow and get back to you.

**Comment by NeillHerbst** [comment]
I installed v0.2 of ZOOpt and ran the example you suggested.

The following error was raised:
```
File "C:\Users\****\Anaconda3\lib\site-packages\zoopt\algos\opt_algorithms\paretoopt\pareto_optimization.py", line 11, in <module>
    from paretoopt import ParetoOpt
ModuleNotFoundError: No module named 'paretoopt'
```

For reference, I'm using the Anaconda (v5.1) distribution of Python on Windows 10.

**Comment by AlexLiuyuren** [comment]
Thank you for your issue. We have fixed this bug and will update the release version in a while. To use the latest version, please:
1.  pip uninstall zoopt
2. download this repository, and sequentially run following commands in your terminal/command line.
```
$ python setup.py build
$ python setup.py install
```
I think the latest version will work well.
